import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import { CartProvider } from "@/context/CartContext"; // সঠিক import
import { AuthProvider } from "@/context/AuthContext";
import Footer from "./components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* CartProvider ব্যবহার করতে হবে */}
      <AuthProvider> 
         <CartProvider>
          <Navbar />
          {children}
        </CartProvider>
        </AuthProvider>
     <Footer></Footer>
      </body>
    </html>
  );
}